Fix AttributeError: 'gi.repository.Gtk' object has no attribute 'GenericTreeModel'
Gtk3 doesn't provide GenericTreeModel, Add compatibility in generictreemodel.py